name: Laravel

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE }}
          port: ${{ secrets.SSH_PORT }}
          args: --script 'cd /var/www/watchdog' --script 'git checkout -f' --script 'git pull' --script 'composer install'
